#ifndef CODE_DEF_H
#define CODE_DEF_H

// メインステート
typedef enum
{
  ANALYZER_IDLE,
  ANALYZER_COMPLETE,

  ANALYZER_DC,
  ANALYZER_AC,
  ANALYZER_MEASURE_DC,
  ANALYZER_MEASURE_AC,
  ANALYZER_HPF,
  ANALYZER_VOFFSET,
  ANALYZER_WAIT,

  ANALYZER_CC,
  ANALYZER_CV,
  ANALYZER_CHARGE_CC,
  ANALYZER_CHARGE_CCCV,
  ANALYZER_WAIT_MEASURE,

  ANALYZER_WHOAMI,
  ANALYZER_CALIBRATE,
  ANALYZER_CALIBRATE_CURRENT,

  ANALYZER_ABORT,
} AnalyzerStateTypeDef;

// エラーコード
typedef enum
{
  // エラーステート
  NO_ERROR,

  // Command
  COMMAND_NOT_FOUND,

  // Stop command
  COMMAND_ABORT,

  // Setter functions
  INVALID_PARAMETER_NUM,
  INVALID_PARAMETER_RANGE,

  // ADC
  ADC_START_FAILURE,
  ADC_STOP_FAILURE,

  ADC_MULTIMODE_SET_FAILURE,
  ADC_CHANNEL_SET_FAILURE,

  ADC_DMA_TRANSFER_FAILURE,
  ADC_INTERNAL_FAILURE,
  ADC_OVERRUN_FAILURE,

  // DAC
  DAC_START_FAILURE,
  DAC_STOP_FAILURE,
  DAC_SET_FAILURE,

  // Watchdog
  VOLTAGE_UPPER_LIMIT,
  VOLTAGE_LOWER_LIMIT,

  // UART
  UART_UNHANDLED_FAILURE,

  // Stack
  STACK_OVERFLOW,
  STACK_UNDERFLOW,

  // Data
  WRITE_DATA_FAILURE,

  // Memory
  MEMORY_ALLOCATION_FAILURE,

  // Wildcard
  UNKNOWN_ERROR,
} AnalyzerErrorTypeDef;

// 内部で使用される状態
typedef enum
{
  ANALYZER_INTERNAL_READY,
  ANALYZER_INTERNAL_BUSY,
  ANALYZER_INTERNAL_COMPLETE,
} AnalyzerInternalStateTypeDef;

#endif
